// LAWMA Official PSP Operators (from Truck Validation Report)
// 446 operators, 57 LGAs, 492 ward assignments
// Generated: 2026-05-21
// Format: n=name, a=assignments, l=LGA, w=ward, t=truck count
var pspOperators = [
  {n:"AJ Mercy",a:[{"l":"Agbado Oke-Odo","w":"MOSHALASHI","t":"4"}]},
  {n:"Aachener Ventures",a:[{"l":"Iba","w":"IBA HOUSING ESTATE","t":"2"},{"l":"Iba","w":"IBA III","t":"1"}]},
  {n:"Aare One",a:[{"l":"Agbado Oke-Odo","w":"MEIRAN II","t":"1"}]},
  {n:"Abake Toyin Enterprises",a:[{"l":"Odi-Olowo Ojuwoye","w":"OWODUNNI","t":"3"}]},
  {n:"Abfad Global Resources",a:[{"l":"Coker Aguda","w":"IRONE II","t":"1"}]},
  {n:"Abikelayo Global",a:[{"l":"Ijede","w":"WARD A & D","t":"2"}]},
  {n:"Accord Energy",a:[{"l":"Eti-Osa East","w":"ABRAHAM ADESANYA ESTATE","t":"1"}]},
  {n:"Adel Integrated",a:[{"l":"Imota","w":"SLOT B IMOTA","t":"0"}]},
  {n:"Adelite Global Resources",a:[{"l":"Ejigbo","w":"AILEGUN II","t":"2"}]},
  {n:"Adept Clean",a:[{"l":"Igando Ikotun","w":"IKOTUN","t":"3"}]},
  {n:"Adeysleek Enterprises",a:[{"l":"Ikosi Isheri","w":"RIVER VILLE ESTATE (LSDPC)","t":"1"},{"l":"Mosan Okunola","w":"MOSAN/ AKINOGUN I","t":"1"}]},
  {n:"Advanced Waste Project",a:[{"l":"Orile Agege","w":"ORILE","t":"2"}]},
  {n:"Afo Ventures",a:[{"l":"Ojokoro","w":"ALAKUKO","t":"1"},{"l":"Orile Agege","w":"PAPA ASHAFA II","t":"1"}]},
  {n:"Afosco Environmental",a:[{"l":"Ikorodu Central","w":"SLOT A OLAJOMEHIN (EYITA)","t":"2"}]},
  {n:"Agoa Waste",a:[{"l":"Olorunda","w":"AGBARA-ARADAGUN (R)","t":"1"}]},
  {n:"Aisaoo",a:[{"l":"Egbe Idimu","w":"EGBE AGODO I","t":"2"}]},
  {n:"Ajwaco Nig Ent",a:[{"l":"Ori-Ade","w":"KIRIKIRI","t":"4"}]},
  {n:"Akin Clean Ventures",a:[{"l":"Ikorodu West","w":"EBUTE/IPAKODO","t":"1"},{"l":"Kosofe","w":"OGUDU ORI OKE","t":"1"}]},
  {n:"Akin Fashina",a:[{"l":"Alimosho","w":"ALABATA","t":"2"}]},
  {n:"Akinsjohn Environmental",a:[{"l":"Agege","w":"ATOBAJE II","t":"1"},{"l":"Ifako Ijaiye","w":"OYEMEKUN II","t":"1"}]},
  {n:"Al -Sheuk Ventures",a:[{"l":"Ibeju Lekki","w":"ORIBANWA - BOGIJE (LEFT SIDE)","t":"2"}]},
  {n:"Al-Wajud Labom",a:[{"l":"Oto Awori","w":"IJANIKIN","t":"1"}]},
  {n:"Alba Nigeria Limited",a:[{"l":"Eti Osa West","w":"FROM LEKKI GATE, ALL LEFT TO IKOYI BRIDGE AND BISOLA DUROSINMI RIGHT TO ROAD 14 ADEBAYO DOHERTY AND FOLA OSIBO ALL RIGHT TO HAKEEM DICKSON","t":"6"}]},
  {n:"Allied Waste Services",a:[{"l":"Odi-Olowo Ojuwoye","w":"ILUPEJU INDUSTRIAL","t":"5"}]},
  {n:"Aloy Udeson Ventures",a:[{"l":"Mushin Ajina","w":"ONITIRE","t":"2"}]},
  {n:"Alpha Waste Management Servies Ltd",a:[{"l":"Yaba","w":"ADEKUNLE/AYETORO HARVEY ROAD ALAGOMEJI","t":"4"}]},
  {n:"Amazing Aat Intermix",a:[{"l":"Alimosho","w":"AKOWONJO II","t":"2"}]},
  {n:"Amboes Trading",a:[{"l":"Ojo","w":"IRA","t":"3"}]},
  {n:"Amote Enterprises",a:[{"l":"Ikoyi/ Obalende","w":"FROM FRENCH EMBASSY (QUEEN\u0092S DRIVE) TO RIGHT SIDE OF BOUDILLON TO ALEXANDRA (RIGHT SIDE) TO RIGHT SIDE OF GERRALD TO ELEGANZA HOUSE (RIGHT SIDE) ON IKOYI CRESCENT","t":"3"}]},
  {n:"Amuleya Nig Ltd",a:[{"l":"Badagry Central","w":"IKOGA, ISALU/IYAFIN, AJIDO, AJARA TOPA, AJARA VETHO","t":"1"}]},
  {n:"Anayas Ventures",a:[{"l":"Coker Aguda","w":"IRONE I","t":"1"}]},
  {n:"Anjolaoluwa Israel Enterprise",a:[{"l":"Isolo","w":"AKINBAIYE","t":"2"}]},
  {n:"Annystar Nig Ent",a:[{"l":"Ikorodu Central","w":"SLOT A ITUPATE","t":"0"}]},
  {n:"Archer Environclean",a:[{"l":"Ikeja","w":"ALADE","t":"5"},{"l":"Ikeja","w":"ANIFOWOSHE","t":"5"},{"l":"Ikeja","w":"ORILE IKEJA","t":"6"}]},
  {n:"Ariesmikky Ent",a:[{"l":"Iba","w":"IBA II","t":"2"},{"l":"Iba","w":"ISASHI","t":"2"}]},
  {n:"Ashybay Nig Ltd",a:[{"l":"Ifako Ijaiye","w":"IJU ISHAGA I","t":"2"}]},
  {n:"Aspot Ventures",a:[{"l":"Igbogbo Bayeku","w":"SLOT B WARD C1, ABOSAN","t":"1"}]},
  {n:"Audu & Sons",a:[{"l":"Apapa","w":"ANJORIN","t":"3"}]},
  {n:"Augustine Okeke And Sons",a:[{"l":"Ikoyi/ Obalende","w":"DOLPHIN/DOLPHIN EXT","t":"2"}]},
  {n:"Aylinka Waste",a:[{"l":"Apapa","w":"ODUDUWA II","t":"1"}]},
  {n:"Ayobami Waste Company",a:[{"l":"Odi-Olowo Ojuwoye","w":"IDI ORO","t":"ABSCONDED"}]},
  {n:"Ayolade Oluwabukola Enterprises",a:[{"l":"Lagos Island East","w":"AJELE","t":"0"}]},
  {n:"Ayomide Olayinka Ventures",a:[{"l":"Kosofe","w":"OLUBORI/MOSAFEJO","t":"2"}]},
  {n:"Azeemah Gold",a:[{"l":"Igando Ikotun","w":"AKESAN I","t":"2"}]},
  {n:"B.Kay Plus Global",a:[{"l":"Ikorodu Central","w":"SLOT B OLAJOMEHIN (EYITA)","t":"2"}]},
  {n:"B.S Passion",a:[{"l":"Ikosi Ejinrin","w":"AGBOWA","t":"1"}]},
  {n:"Backarey Ecoflow Ent",a:[{"l":"Igando Ikotun","w":"IJEDODO II","t":"1"},{"l":"Itire-Ikate","w":"AIRWAYS II","t":"1"}]},
  {n:"Backhome",a:[{"l":"Eti-Osa East","w":"FROM TOTAL FILLING STATION TO OKE IRA BRIDGE/ GOOD HOMES","t":"2"}]},
  {n:"Bailas Nigeria Company",a:[{"l":"Ojo","w":"SABO ONIBA","t":"2"}]},
  {n:"Bakom Nig Compaany",a:[{"l":"Ikorodu North","w":"ITA OLUWO/OLOPOMEJI/ODONGUNYAN","t":"1"}]},
  {n:"Bamitonia And Company",a:[{"l":"Ikoyi/ Obalende","w":"OBALENDE I","t":"4"}]},
  {n:"Bamowo Ent",a:[{"l":"Ajeromi","w":"AJEGUNLE","t":"1"}]},
  {n:"Banabasty Enterprise",a:[{"l":"Ayobo Ipaja","w":"SLOT B AYOBO","t":"2"}]},
  {n:"Banuso Court Ltd",a:[{"l":"Surulere","w":"OBELE ONIWALA","t":"2"}]},
  {n:"Bauh Bon Environmental",a:[{"l":"Mushin Ajina","w":"ALAAFIA ADEOYO","t":"3"},{"l":"Mushin Ajina","w":"ATEWOLARA","t":"3"},{"l":"Mushin Ajina","w":"PAPA AJAO","t":"3"}]},
  {n:"Best Buy Trading",a:[{"l":"Agbado Oke-Odo","w":"IGOKE","t":"2"}]},
  {n:"Billie Taiwo",a:[{"l":"Ibeju Lekki","w":"ELEKO - AKODO","t":"2"}]},
  {n:"Bimken Ventures",a:[{"l":"Ikorodu North","w":"SLOT A AGBEDE","t":"1"}]},
  {n:"Biospheres Technologies",a:[{"l":"Apapa Iganmu","w":"ABETE","t":"0"},{"l":"Apapa Iganmu","w":"BADIA","t":"0"},{"l":"Apapa Iganmu","w":"OWOSENI","t":"1"}]},
  {n:"Bisiolu Nigeria Enterprises",a:[{"l":"Igando Ikotun","w":"IGANDO","t":"2"}]},
  {n:"Bismitop Global Ventures",a:[{"l":"Ikorodu West","w":"OWUTU/AGRIC","t":"2"}]},
  {n:"Bivitol Wast Mgt",a:[{"l":"Kosofe","w":"SOLUYI","t":"2"}]},
  {n:"Blackwater Technology",a:[{"l":"Eti-Osa East","w":"FROM DOMINO TO NEW ROAD BUS STOP OLAJIDE PLAZA (RIGHT & LEFT)","t":"2"}]},
  {n:"Blessing Bolu",a:[{"l":"Eti-Osa East","w":"ROYAL GARDEN ESTATE TO ABRAHAM ADESANYA ESTATE/LEKKI SCHEME 2 TO OGOMBO TOWN","t":"5"}]},
  {n:"Blue Line Concept",a:[{"l":"Igbogbo Bayeku","w":"SLOT A,WARD C2 IGBOGBO","t":"2"}]},
  {n:"Bod Evironmental Services",a:[{"l":"Ikoyi/ Obalende","w":"OBALENDE LOCAL GOVERNMENT TO GOLDEN GATE(LEFT SIDE) AND GOLDEN GATE TO IKOYI REGISTRY ON ALFRED REWANE (RIGHT)","t":"3"}]},
  {n:"Boiise Trust",a:[{"l":"Agbado Oke-Odo","w":"AJASA","t":"2"},{"l":"Mosan Okunola","w":"OKUNOLA II","t":"3"}]},
  {n:"Boltram",a:[{"l":"Igando Ikotun","w":"IJEDODO I","t":"0"}]},
  {n:"Boltram Nigeria Limited",a:[{"l":"Ejigbo","w":"AIGBAKA II","t":"2"}]},
  {n:"Bosunand Global",a:[{"l":"Igando Ikotun","w":"IJEGUN I","t":"2"},{"l":"Igando Ikotun","w":"ISHERI OSHUN II","t":"2"}]},
  {n:"Brecknok Nigeria Limited",a:[{"l":"Isolo","w":"CANAL VIEW","t":"2"}]},
  {n:"Bright Environmental Work Ltd",a:[{"l":"Apapa","w":"WARD II GRA APAPA","t":"2"}]},
  {n:"Bucklad Nigeria Limited",a:[{"l":"Oshodi","w":"MAFOLUKU","t":"2"}]},
  {n:"Busol Global",a:[{"l":"Agboyi Ketu","w":"OSHOGUN","t":"2"}]},
  {n:"Cabistolat Nigeria Limited",a:[{"l":"Lagos Mainland","w":"OJO ONIYUN","t":"1"}]},
  {n:"Capital Gee Ventures",a:[{"l":"Mushin Ajina","w":"IGBEHINADUN III","t":"2"}]},
  {n:"Carlydine Investment",a:[{"l":"Amuwo Odofin","w":"IREPODUN","t":"2"}]},
  {n:"Carmel",a:[{"l":"Eti Osa West","w":"FOLA OSIBO ALL LEFT FROM HAKEEM DICKSON TO THE GATE TO BADERI ALABI","t":"3"}]},
  {n:"Carofad Global",a:[{"l":"Igbogbo Bayeku","w":"BAYEKU WARD","t":"2"}]},
  {n:"Century Cleaners",a:[{"l":"Surulere","w":"ADENIRAN OGUNSANYA","t":"4"},{"l":"Surulere","w":"ARALILE","t":"2"},{"l":"Surulere","w":"IPONRI/ ERIC MOORE","t":"2"}]},
  {n:"Cheliz-Don Integrated Services Limited",a:[{"l":"Isolo","w":"AGO PALACE II","t":"2"}]},
  {n:"Chicago Waste Project",a:[{"l":"Ikosi Isheri","w":"AGILITI/MAIDAN","t":"1"}]},
  {n:"Christoclear",a:[{"l":"Agbado Oke-Odo","w":"AGBADO","t":"4"}]},
  {n:"Clean & Convert Nig Ltd",a:[{"l":"Ifelodun","w":"LAYENI","t":"1"}]},
  {n:"Clean Clear Vent",a:[{"l":"Ojodu","w":"OKEIRA CENTRAL II","t":"2"}]},
  {n:"Clean Craft",a:[{"l":"Igando Ikotun","w":"ISHERI OSHUN I","t":"2"}]},
  {n:"Clean Deal Reality",a:[{"l":"Eti Osa West","w":"HARRIS DRIVE","t":"2"}]},
  {n:"Clean Harbour Environmental Services",a:[{"l":"Ejigbo","w":"ILAMOSE","t":"2"}]},
  {n:"Cleaner Royal Venturrs Limited",a:[{"l":"Isolo","w":"AJAO ESTATE II","t":"2"}]},
  {n:"Cleanway Limited",a:[{"l":"Iru/ Victoria Island","w":"NIGERIAN LAW SCHOOL ON OZUMBA MBADIWE TO AKIN ADESOLA (EXCLUDING AHMADU BELLO AND ADEMOLA ADETOKUNBO)","t":"2"}]},
  {n:"Cogence Continetal",a:[{"l":"Bariga","w":"SERIKI OKUTA","t":"2"}]},
  {n:"Cogence Continnetal",a:[{"l":"Ojodu","w":"OLUWOLE/SHOGUNRO/ENAHORO","t":"1"}]},
  {n:"Compost Integrated",a:[{"l":"Eredo","w":"EREDO (SLOT B)","t":"2"}]},
  {n:"Conscience Waste",a:[{"l":"Igando Ikotun","w":"ABARANJE IV","t":"1"}]},
  {n:"Continental Waste",a:[{"l":"Apapa","w":"ABRAHAM ADESANYA I","t":"3"}]},
  {n:"Continental Waste Mngt",a:[{"l":"Apapa Iganmu","w":"SARI","t":"2"}]},
  {n:"Cornerstone Unique Concept",a:[{"l":"Mosan Okunola","w":"ABESAN I","t":"2"}]},
  {n:"Cosmopolitan",a:[{"l":"Agege","w":"KEKE II","t":"2"}]},
  {n:"Cosmopolitan Cleaners",a:[{"l":"Eti Osa West","w":"PERIWINKLE, FARMVILLA, HAMPTON LAKE, DAFFODIL GARDEN, TREM, MAIYEGUN, ORANGE ISLAND, RIVEIRA COURT, VALLEY STREAM & FRIENDS COLONY","t":"2"}]},
  {n:"Crown & Mine",a:[{"l":"Apapa","w":"ABRAHAM ADESANYA II","t":"1"}]},
  {n:"Crystallios",a:[{"l":"Ikoyi/ Obalende","w":"REEVE TOWERS","t":"2"}]},
  {n:"Cuttysark",a:[{"l":"Eti Osa West","w":"FROM IKOYI BRIDGE ALL LEFT TO BABATUNDE ANJORIN AND ADMIRALTY ROAD TO FATAI IDOWU AROBIEKE","t":"3"}]},
  {n:"D Nigeria",a:[{"l":"Eti-Osa East","w":"PART OF WARD A (FROM FILLING STATION ADDO ROAD (LEFT) VIA AJAH JUBILEE BRIDGE TO ABRAHAM ADESANYA JUNCTION,","t":"3"},{"l":"Eti-Osa East","w":"VICTORIA GARDEN CITY (PART)","t":"2"}]},
  {n:"Dalmatex International",a:[{"l":"Kosofe","w":"ORILE OWORO","t":"2"}]},
  {n:"Dalson Global Bus Waste",a:[{"l":"Egbe Idimu","w":"IDIMU I","t":"2"}]},
  {n:"Damilola Consolidated",a:[{"l":"Ojodu","w":"AGUDA","t":"2"}]},
  {n:"Danad Waste Services",a:[{"l":"Mushin Ajina","w":"IDI ARABA","t":"2"}]},
  {n:"Danhit Focus",a:[{"l":"Alimosho","w":"ALAGUNTAN","t":"2"}]},
  {n:"Day Facilities Management And Procurement Limited",a:[{"l":"Onigbongbo","w":"AREA F POLICE BARRACK & MOPOL 20 BARRACK GRA","t":"1"}]},
  {n:"De Enhancer",a:[{"l":"Agbado Oke-Odo","w":"IKOLA","t":"2"}]},
  {n:"De Top Notch",a:[{"l":"Lekki Lcda","w":"IDOTUN - OSHOROKO","t":"2"}]},
  {n:"Debby Hefsibah Consult",a:[{"l":"Eti Osa West","w":"CIRCLE MALL (SHOPRITE) TO CHEVRON DRIVE JUNCTION","t":"3"}]},
  {n:"Debmicharryneal Great Ventures",a:[{"l":"Coker Aguda","w":"OSHO","t":"2"}]},
  {n:"Decoren Waste Project",a:[{"l":"Iba","w":"CELENIZER","t":"2"}]},
  {n:"Defsolut",a:[{"l":"Eti Osa West","w":"BERRA ESTATE","t":"1"}]},
  {n:"Dejyle Ent",a:[{"l":"Ifako Ijaiye","w":"IFAKO","t":"2"},{"l":"Ifako Ijaiye","w":"OBAWOLE","t":"2"}]},
  {n:"Dek Enterprises",a:[{"l":"Odi-Olowo Ojuwoye","w":"BABALOSHA","t":"2"}]},
  {n:"Delola Medum And Sons",a:[{"l":"Igando Ikotun","w":"ABARANJE I","t":"2"}]},
  {n:"Deniks Enterprises",a:[{"l":"Ikosi Isheri","w":"SLOT A ISHERI NORTH ESTATE","t":"1"},{"l":"Ikoyi/ Obalende","w":"FROM GOLDEN GATE (RIGHT SIDE) TO DEFENCE HOUSE TO OSBORNE ROAD","t":"1"}]},
  {n:"Deshasat Ent.",a:[{"l":"Olorunda","w":"ARADAGUN-BADAGRY(R)","t":"1"}]},
  {n:"Dewayls",a:[{"l":"Ori-Ade","w":"IJEGUN EMURE","t":"1"}]},
  {n:"Diadem Nigeria Limited",a:[{"l":"Ikoyi/ Obalende","w":"ABRAHAM ADESANYA TO OKO ADO TO SANGOTEDO (LEFT) TO SANGOTEDO MARKET","t":"4"}]},
  {n:"Discovery Logistics",a:[{"l":"Ajeromi","w":"ALAKOTO","t":"2"},{"l":"Ajeromi","w":"TEMIDIRE","t":"1"}]},
  {n:"Divyn Exclusive",a:[{"l":"Bariga","w":"AYETORO/MAFOWOKU","t":"2"}]},
  {n:"Dopec Nig Ent",a:[{"l":"Agboyi Ketu","w":"AROWOSEGBE/ALAPERE","t":"2"}]},
  {n:"Dorosas Global Services Limited",a:[{"l":"Ejigbo","w":"FADU","t":"2"}]},
  {n:"Dosetwill Ventures",a:[{"l":"Mushin Ajina","w":"IGBEHINADUN I","t":"2"}]},
  {n:"Dotyem Ent",a:[{"l":"Agege","w":"AWORI ONIWAYA","t":"2"}]},
  {n:"Double D Medley",a:[{"l":"Ikoyi/ Obalende","w":"OLAWALE DAODU ROAD, OLUMEGBON ROAD, OLUWA ROAD, AROMIRE ROAD, RUMENS ROAD, OTUNBA BIMBO ASHIRU","t":"2"}]},
  {n:"Doveroost Ltd",a:[{"l":"Eti Osa West","w":"PURPLE WAY JUNCTION TO FREEDOM WAY JUNCTION TO OBA YEKINI ELEGUSHI STREET OFF LEKKI EPE EXPRESSWAY (LEFT) THROUGH TO GBANGBALA (LEFT) AND TERMINATES AT ORE FAMEWO (LEFT SIDE) EXCLUDING TREASURE GARDEN AND PRIME WATER GARDEN I & II","t":"1"}]},
  {n:"Dunqube Cleaning Services",a:[{"l":"Ojodu","w":"OGBA","t":"1"}]},
  {n:"Dustbin Boy Solutions",a:[{"l":"Eti-Osa East","w":"HARMONY & UNITY ESTATE","t":"1"}]},
  {n:"Duvak Global Resources",a:[{"l":"Ifelodun","w":"OJORA (WARD F)","t":"1"}]},
  {n:"Edwex",a:[{"l":"Alimosho","w":"AKOWONJO I","t":"2"}]},
  {n:"Elawsund Nig Ent",a:[{"l":"Agboyi Ketu","w":"AGIDI","t":"2"}]},
  {n:"Elu K And Sons",a:[{"l":"Ikorodu West","w":"IGBO OLOMU","t":"1"}]},
  {n:"Emestar Logistics",a:[{"l":"Igando Ikotun","w":"EGAN III","t":"2"}]},
  {n:"Endeavour Environmental Services",a:[{"l":"Bariga","w":"AKOKA/ANUOLUWAPO","t":"2"}]},
  {n:"Enimaria",a:[{"l":"Eti-Osa East","w":"OKO ADO TO SANGOTEDO (LEFT)","t":"2"}]},
  {n:"Environ Geotech Solution",a:[{"l":"Ikoyi/ Obalende","w":"BANANA ISLAND EXTENSION","t":"1"}]},
  {n:"Esosom Nigeria Limited",a:[{"l":"Oshodi","w":"OGUN OLOKO","t":"2"}]},
  {n:"Estey Dee Ventures",a:[{"l":"Odi-Olowo Ojuwoye","w":"OJUWOYE","t":"2"}]},
  {n:"Eugbest Ind Control",a:[{"l":"Oto Awori","w":"ETEGBIN","t":"2"}]},
  {n:"Evabol Vent",a:[{"l":"Ajeromi","w":"OLUWA I","t":"1"}]},
  {n:"Excellens Link Limited",a:[{"l":"Oshodi","w":"AFARIOGUN","t":"4"},{"l":"Oshodi","w":"OLUYEYE","t":"4"}]},
  {n:"Express General Logistics",a:[{"l":"Bariga","w":"IBUOWO/OWOTUTU","t":"2"}]},
  {n:"Ezzeco",a:[{"l":"Eti Osa West","w":"CHEVRON DRIVE","t":"2"}]},
  {n:"F .A. Unique Concept",a:[{"l":"Ojo","w":"OJO TOWN","t":"2"}]},
  {n:"F A Unique Concept",a:[{"l":"Iba","w":"AJANGBADI","t":"2"}]},
  {n:"F.T Baylek Nig. Ent.",a:[{"l":"Ikorodu North","w":"ODUYEBO/ROFO/ODONGUNYAN","t":"2"}]},
  {n:"Fabbey Resources Limited",a:[{"l":"Ifelodun","w":"OKE OJA (WARD E)","t":"1"}]},
  {n:"Fadun Nigeria Limited",a:[{"l":"Ikoyi/ Obalende","w":"OBALENDE II","t":"3"}]},
  {n:"Faith & Blessing",a:[{"l":"Ayobo Ipaja","w":"BARUWA II","t":"2"},{"l":"Egbe Idimu","w":"UNITY ESTATE II","t":"2"}]},
  {n:"Fajoe Global Ventures",a:[{"l":"Ikorodu Central","w":"SLOT B AGURA GBERIGBE","t":"2"}]},
  {n:"Favoreno Global Services",a:[{"l":"Surulere","w":"SHITTA BANK-OLEMOH","t":"1"}]},
  {n:"Felso",a:[{"l":"Eti Osa West","w":"OKUN AJAH A","t":"4"}]},
  {n:"Femfash Petrolueum ;Limited",a:[{"l":"Iba","w":"TRINITY/CHURCH","t":"2"}]},
  {n:"Fenidols Investment Ltd",a:[{"l":"Ojodu","w":"AKIODE I","t":"2"}]},
  {n:"Fesfel & Vic Limited",a:[{"l":"Ayobo Ipaja","w":"BARUWA 1","t":"2"}]},
  {n:"Firstmay",a:[{"l":"Eti Osa West","w":"PART OF VGC","t":"2"}]},
  {n:"Fjd Cleaning",a:[{"l":"Bariga","w":"ILAJE","t":"1"}]},
  {n:"Fountain Multiple Vent",a:[{"l":"Ifako Ijaiye","w":"IJU/OMO OINLE","t":"2"}]},
  {n:"Fumab Ent",a:[{"l":"Agbado Oke-Odo","w":"ABULE EGBA II","t":"2"}]},
  {n:"Fumdammy Ventures\n(Formerly Jemon Ventures)",a:[{"l":"Ikorodu Central","w":"SLOT A AGA OJOMU","t":"1"}]},
  {n:"G Streams & Gears",a:[{"l":"Itire-Ikate","w":"RAMONI","t":"2"}]},
  {n:"Gabwaste Global Ventures",a:[{"l":"Ikorodu North","w":"SLOT B PARAFA/LUCKY FIBRE","t":"1"}]},
  {n:"Gafista Concept",a:[{"l":"Apapa","w":"ODUDUWA","t":"2"}]},
  {n:"Galaxy  Waste Services",a:[{"l":"Mushin Ajina","w":"ODESELUOLA","t":"2"}]},
  {n:"Gbola Agbeke And Sons",a:[{"l":"Ayobo Ipaja","w":"ATAN ii","t":"2"},{"l":"Ayobo Ipaja","w":"ATAN ii","t":"2"}]},
  {n:"Gboleybos Ent.",a:[{"l":"Igbogbo Bayeku","w":"SLOT A, WARD C1, OLUODO/AWOBO","t":"2"}]},
  {n:"Gee Mony Global Kleaners",a:[{"l":"Ikorodu North","w":"SLOT A PARAFA LUCKY FIBRE","t":"1"}]},
  {n:"Gidium Nig Ent",a:[{"l":"Ikorodu Central","w":"SLOT A, AGURA GBERIGBE","t":"2"}]},
  {n:"Give & Keep Turning Point",a:[{"l":"Surulere","w":"GBAJA OBELE ODAN","t":"1"}]},
  {n:"Global Gold Duke",a:[{"l":"Igando Ikotun","w":"BADORE","t":"2"}]},
  {n:"Glorious Rise Ent",a:[{"l":"Amuwo Odofin","w":"IFELODUN","t":"2"},{"l":"Itire-Ikate","w":"OGUNSANMI/KAROUNWI","t":"2"}]},
  {n:"Golden Pond Limited",a:[{"l":"Ejigbo","w":"JAKANDE","t":"2"}]},
  {n:"Golden Rising",a:[{"l":"Alimosho","w":"SANTOS/ ILUPEJU","t":"3"}]},
  {n:"Grace Emma Int'L Vent",a:[{"l":"Agbado Oke-Odo","w":"OKE ALAGUNTAN","t":"2"}]},
  {n:"Great Abbey Discoveries",a:[{"l":"Lagos Mainland","w":"ARAROMI","t":"1"}]},
  {n:"Great Wuyi Vent",a:[{"l":"Ojodu","w":"OKEIRA CENTRAL I","t":"2"}]},
  {n:"Green Kleaners",a:[{"l":"Ibeju Lekki","w":"ABIJO - BOJIGE (RHS)","t":"2"}]},
  {n:"Grenstone Ltd",a:[{"l":"Ikoyi/ Obalende","w":"FROM IKOYI CRESCENT TO BOTH PARKVIEW ESTATE JUNCTION (LEFT) AND LAWRENCE ROAD JUNCTION (RIGHT) ON GERRADE RD ( ALL BUILDINGS EXCEPT COCACOLA BUILDING","t":"2"}]},
  {n:"Guestimate Environmental",a:[{"l":"Agege","w":"SANGO","t":"2"},{"l":"Orile Agege","w":"POWERLINE/OKO OBA","t":"2"}]},
  {n:"H.H Diamond Enterprises",a:[{"l":"Mushin Ajina","w":"IGBEHINADUN","t":"2"}]},
  {n:"H.H. Diamond Enterprises",a:[{"l":"Itire-Ikate","w":"AIRWAYS I","t":"1"}]},
  {n:"HCI",a:[{"l":"Agbado Oke-Odo","w":"OKE ODO II","t":"3"}]},
  {n:"Hadal & Sons",a:[{"l":"Mosan Okunola","w":"GOWON ESTATE","t":"2"}]},
  {n:"Hakbas Ventures",a:[{"l":"Egbe Idimu","w":"IDIMU II","t":"2"}]},
  {n:"Hakolan Waste Services",a:[{"l":"Coker Aguda","w":"JINADU AYETORO","t":"1"}]},
  {n:"Hammer Engineering",a:[{"l":"Eti Osa West","w":"FROM IKOYI BRIDGE ALL LEFT TO BABATUNDE ANJORIN AND ADMIRALTY ROAD TO FATAI IDOWU AROBIEKE","t":"1"}]},
  {n:"Headmaster Nig Ltd",a:[{"l":"Ikeja","w":"MARWA GARDEN","t":"2"}]},
  {n:"Hephzibah Integrated",a:[{"l":"Eti Osa West","w":"PALM SPRING ROAD/SALEM STREET TO HONORABLE YAYA DOSUMU WAY","t":"6"}]},
  {n:"Hes Solution",a:[{"l":"Ibeju Lekki","w":"ALAHUN - IBEJU (RHS)","t":"2"}]},
  {n:"Hidef Concept And Logistics",a:[{"l":"Eti-Osa East","w":"IKOTA/ILAJE/ETI OSA RESETTLEMENT/MOBIL ROAD AND ENVIRON","t":"4"}]},
  {n:"Horlag",a:[{"l":"Eredo","w":"EREDO (SLOT A)","t":"2"}]},
  {n:"House Keeper",a:[{"l":"Ikoyi/ Obalende","w":"DOLPHIN/ABDULAHI ADAMU ESTATES","t":"3"}]},
  {n:"Ifelodun Waste Collectors",a:[{"l":"Ifelodun","w":"OWOYEMI","t":""}]},
  {n:"Immaculate Environmental",a:[{"l":"Kosofe","w":"OGUDU GRA","t":"3"}]},
  {n:"Immaculate Environmental Services",a:[{"l":"Eti Osa West","w":"PRIME WATER VIEW GARDEN 1&2 ESTATES ON ENGR. TAIWO ODEFUNSO STREET OFF FREEDOM WAY, IKATE","t":"1"}]},
  {n:"Imperial Facility",a:[{"l":"Eti Osa West","w":"CHEVRON DRIVE TO VICTORIAL CREST ESTATE","t":"2"}]},
  {n:"Imperium",a:[{"l":"Agbado Oke-Odo","w":"AMIKANLE III","t":"2"}]},
  {n:"Influencial Global Resources",a:[{"l":"Igando Ikotun","w":"ABULE ONILU/IDOWU EGBA","t":"2"}]},
  {n:"Iroko Awe",a:[{"l":"Eti Osa West","w":"ILASAN (LEFT) TO JAKANDE FIRST GATE (RIGHT)","t":"5"}]},
  {n:"It-Shad Global",a:[{"l":"Agboyi Ketu","w":"ODOGUN/AJEGUNLE","t":"2"}]},
  {n:"Itechsol Global",a:[{"l":"Lagos Mainland","w":"GLOVER FREEMAN","t":"2"}]},
  {n:"Iyalaje Waste Company",a:[{"l":"Alimosho","w":"OMITUNUTUN","t":"3"}]},
  {n:"Iyenoma Omoromtiomwan And Sons",a:[{"l":"Ikoyi/ Obalende","w":"LAWRENCE RD (LEFT) TO SUBOMI/FCMB ROUNDABOUT TO MILVERTON STR & ALL BUILDINGS ON BOURDILLION ROAD FROM THOMPSON AVENUE JUNCTION (LEFT) TO ALEXANDER ROUNDABOUT JUNCTION(LEFT).","t":"2"}]},
  {n:"Janney Global",a:[{"l":"Bariga","w":"PEDRO","t":"2"}]},
  {n:"Jeffery Abiodun Ent.",a:[{"l":"Igbogbo Bayeku","w":"SLOT B IBESHE WARD","t":"2"}]},
  {n:"Jelots Limited",a:[{"l":"Isolo","w":"AGO PALACE I","t":"1"}]},
  {n:"Jerrimug Ventures",a:[{"l":"Yaba","w":"ADERUPOKO/IJEBU QTRS SALAMI AYEWU MAKOKO","t":"2"},{"l":"Yaba","w":"MAKOKO","t":"2"}]},
  {n:"Jiblad Nig Limited",a:[{"l":"Ejigbo","w":"AIGBAKA I","t":"2"}]},
  {n:"Jigzack",a:[{"l":"Eti-Osa East","w":"ADDO R/ABOUT TO RCCG CHURCH","t":"2"}]},
  {n:"Jim-Sif  Global Waste Services",a:[{"l":"Ikosi Isheri","w":"SLOT B ISHERI NORTH ESTATE/OSHORUN/HONEY BROOKES ESTATE","t":"2"},{"l":"Somolu","w":"IGBARI/AKOKA","t":"2"}]},
  {n:"Jimdel And Company",a:[{"l":"Igbogbo Bayeku","w":"SLOT A IBESHE WARD","t":"2"}]},
  {n:"Jimlank Enterprises",a:[{"l":"Lagos Island West","w":"IDUMAGBO","t":"2"}]},
  {n:"Jimmy Resources",a:[{"l":"Egbe Idimu","w":"ISHERI OLOFIN I","t":"2"},{"l":"Igando Ikotun","w":"ABARANJE II","t":"2"}]},
  {n:"Joeati Nig Ltd",a:[{"l":"Amuwo Odofin","w":"ORIRE","t":"2"}]},
  {n:"Jofak Engineering",a:[{"l":"Agbado Oke-Odo","w":"MEIRAN I","t":"2"}]},
  {n:"Jokotex Nig Ent.",a:[{"l":"Ikorodu North","w":"OLORUNDA/MAYA/ADAMO","t":"2"}]},
  {n:"Jolayem Starlite",a:[{"l":"Coker Aguda","w":"BALE","t":"1"}]},
  {n:"Joseph Falode & Sons",a:[{"l":"Ejigbo","w":"AILEGUN I","t":"2"}]},
  {n:"Joskad",a:[{"l":"Igando Ikotun","w":"ABARANJE III","t":"1"}]},
  {n:"Jp Amota",a:[{"l":"Iru/ Victoria Island","w":"ADEMOLA ADETOKUNBO STREET (BOTH SIDES)","t":"5"}]},
  {n:"Judith Ventures",a:[{"l":"Ojokoro","w":"AJEGUNLE","t":"1"}]},
  {n:"Jurichrest Nigeria Limited",a:[{"l":"Eti Osa West","w":"KUSENLA EXCLUDING OJULARI CRESCENT TO IKATE JUNCTION THROUGH TO OBA YEKINI-ELEGUSHI STREET OFF LEKKI EPE EXPRESSWAY (RIGHT) DOWN TO GBANGBALA (RIGHT) AND TERMINATES AT BELLA COURT (IYANUOLUWA BOLAJI STREET OFF CHIEF ORE FAMEWO STREET)","t":"1"}]},
  {n:"Juvicole Int'L",a:[{"l":"Ikorodu Central","w":"SLOT B, (ELUKU, DADA-ITAMAGA)","t":"1"}]},
  {n:"Kamjek Nig Ventures",a:[{"l":"Ojokoro","w":"IJAIYE GBINIRIN","t":"2"}]},
  {n:"Kaygie Enterprises",a:[{"l":"Mosan Okunola","w":"ABESAN II","t":"2"}]},
  {n:"Kazbaj Recycling Nigeria Enterprises",a:[{"l":"Odi-Olowo Ojuwoye","w":"OLATEJU","t":"2"}]},
  {n:"Kazeem Royal Property",a:[{"l":"Eti Osa West","w":"OLEGRA, CANAL WEST ESTATE, INDIGENOUS CHIEF BAMIDELE ELETU & TERMINATES AT MUFUTAU ELETU (LEFT SIDE)","t":"2"}]},
  {n:"Kelkerry Ventures",a:[{"l":"Ikoyi/ Obalende","w":"PARKVIEW ESTATE","t":"4"}]},
  {n:"Kenaal Enterprises",a:[{"l":"Ori-Ade","w":"SATELLITE SLOT B","t":"2"}]},
  {n:"Kenny JPS",a:[{"l":"Alimosho","w":"IFELODUN/ ORISUNBARE","t":"1"},{"l":"Igando Ikotun","w":"EGAN II","t":"1"}]},
  {n:"Kenrate Ventures",a:[{"l":"Ikoyi/ Obalende","w":"THOMPSON AVENUE JUNCTION (LEFT) TO MILVERTON STREET JUNCTION ON GLOVER ROAD (INCLUDING ALL INNER STREET)","t":"2"}]},
  {n:"Kent & Kelly Nig Ltd",a:[{"l":"Kosofe","w":"IFAKO GBAGADA","t":"7"}]},
  {n:"Kim Evironmental",a:[{"l":"Iru/ Victoria Island","w":"AJOSE ADEOGUN ( BOTH SIDES) TO LIGALI AYORINDE","t":"4"}]},
  {n:"Kings And Akins",a:[{"l":"Eti Osa West","w":"BISOLA DUROSINMI ETTI RIGHT TO HAKEEM DICKSON TO THE GATE","t":"2"}]},
  {n:"Kleanpiont",a:[{"l":"Ikosi Isheri","w":"OMOLE PHASE 2/OLOWORA","t":"3"}]},
  {n:"Kleen Habit",a:[{"l":"Agbado Oke-Odo","w":"AMIKANLE II","t":"1"}]},
  {n:"Kleenrite Limited",a:[{"l":"Ori-Ade","w":"KUJE","t":"3"}]},
  {n:"Klinklare Cleaning Services Ltd",a:[{"l":"Apapa Iganmu","w":"MARINE BEACH SLOT, WARD F","t":"1"}]},
  {n:"Klinmate Nigeria Limited",a:[{"l":"Eti-Osa East","w":"HARMONY ESTATE UNITY ESTATE LANFBAS COMMUNITY (LEFT SIDE BEFORE THE LAGOON)","t":"2"},{"l":"Eti-Osa East","w":"ROYAL GARDEN ESTATE","t":"3"}]},
  {n:"Km & O Heritage Limited",a:[{"l":"Isolo","w":"AJAO ESTATE I","t":"3"}]},
  {n:"Kolog Nigeria Limited",a:[{"l":"Eti-Osa East","w":"ABRAHAM ADESANYA TO BLENCO JUNCTION (RIGHT SIDE)","t":"3"}]},
  {n:"Kongi Waste",a:[{"l":"Eti-Osa East","w":"COOPERATIVE TO JETTY, LANGBASA ROAD (RIGHT & LEFT)","t":"2"}]},
  {n:"Korad Closet Empire Ltd",a:[{"l":"Ojodu","w":"OKE IRA/POWERLINE","t":"1"}]},
  {n:"Krestabol Waste",a:[{"l":"Ikorodu Central","w":"LOWA","t":"2"}]},
  {n:"Kunlek Ventures",a:[{"l":"Agboyi Ketu","w":"BANGBE/ELEBIJU","t":"1"},{"l":"Agboyi Ketu","w":"ERUNKAN/ORISHIGUN","t":"1"}]},
  {n:"Kwawell",a:[{"l":"Eti-Osa East","w":"ATLANTIC NOMINEE LTD (ANL) ESTATE, ABIS FARMERS MARKET/ABATTOIR & KWAWEL MALL/PLAZA IN ATLANTIC LAYOUT ESTATE AJIWE","t":"1"}]},
  {n:"LSF Belle",a:[{"l":"Ajeromi","w":"AYETORO","t":"2"}]},
  {n:"Lab Cleaning Services",a:[{"l":"Ayobo Ipaja","w":"BADA/MEGIDA","t":"4"}]},
  {n:"Laibola Link Ltd",a:[{"l":"Badagry Central","w":"POSUKOH, JEGBA QTRS, AWANJIGOH, AHOVIKOH,","t":"1"},{"l":"Badagry West","w":"KWEME (Partly riverine) WESERE (Partly iverine) APA (Partly riverine) AKORO GBETHROME","t":"1"}]},
  {n:"Lakaysak Enterprises",a:[{"l":"Ikorodu Central","w":"OTA ONA","t":"2"}]},
  {n:"Lam Akinbami & Sons",a:[{"l":"Agege","w":"ATOBAJE I","t":"2"}]},
  {n:"Lanphill And Associates",a:[{"l":"Agege","w":"ORILE","t":"2"}]},
  {n:"Latoy Ventures Limited",a:[{"l":"Surulere","w":"RANDLE WARD","t":"2"}]},
  {n:"Lawma",a:[{"l":"Lagos Mainland","w":"OTTO-TOWN","t":"0"}]},
  {n:"Letok & Company",a:[{"l":"Orile Agege","w":"DOPEMU","t":"2"}]},
  {n:"Lion Unisco Enterprises",a:[{"l":"Ikoyi/ Obalende","w":"BANKOLE KADOZO BOUNDARY (LEFT SIDE), PART OF GLOVER, THOMPSON AVENUE, LUGARD AVENUE, CAMERON AVENUE, OLU HOLLOWAY ROAD, ALFRED REWANE ROAD, BAYO KUKU ROAD","t":"2"}]},
  {n:"Lk-Ednut Ventures",a:[{"l":"Ojokoro","w":"ILUPEJU","t":"2"}]},
  {n:"Lollybod Commercial Company",a:[{"l":"Mushin Ajina","w":"BABALOSHA","t":"2"}]},
  {n:"Lucas Carol",a:[{"l":"Iba","w":"OKOKOMAIKO","t":"1"}]},
  {n:"Lummy Integrated Services\n(Formerly Betty Rite Nigeria Limited)",a:[{"l":"Amuwo Odofin","w":"ADO FESTAC","t":"1"}]},
  {n:"M A Ajao Ent",a:[{"l":"Ifelodun","w":"AMUKOKO","t":"2"}]},
  {n:"M.A Allison And Sons",a:[{"l":"Ikorodu North","w":"ODONLA/ODONGUNYAN INDUSTRIAL AREA","t":"4"}]},
  {n:"Mahbok Trading",a:[{"l":"Ikeja","w":"AGIDINGBI","t":"0"}]},
  {n:"Majesty Waste Sevices",a:[{"l":"Ifako Ijaiye","w":"OBAWOLE II","t":"2"}]},
  {n:"Maklad Vibrant",a:[{"l":"Orile Agege","w":"OKE KOTO","t":"2"}]},
  {n:"Makland Vibrant",a:[{"l":"Ikosi Isheri","w":"AVOSEH/MAGODO ESTATE PHASE 1","t":"2"}]},
  {n:"Malib Environmental Company",a:[{"l":"Onigbongbo","w":"OLUSOSUN","t":"2"}]},
  {n:"Maprena",a:[{"l":"Egbe Idimu","w":"UNITY ESTATE III","t":"1"},{"l":"Ojodu","w":"BERGER","t":"1"}]},
  {n:"Marie Gold Ventures",a:[{"l":"Ikosi Isheri","w":"ISHERI/ UNILAG ESTATE","t":"2"}]},
  {n:"Maskot Ade Nig Ent",a:[{"l":"Igbogbo Bayeku","w":"SLOT A EWU ELEPE -IGBE LAARA/ GINTI","t":"2"}]},
  {n:"Matrix Environmental Services",a:[{"l":"Odi-Olowo Ojuwoye","w":"ALAKARA","t":"2"}]},
  {n:"Mc Hall Environmental Services",a:[{"l":"Kosofe","w":"ARAROMI (SAWMILL AREA)","t":"2"}]},
  {n:"Mcking Nig Ltd",a:[{"l":"Ajeromi","w":"ALAYABIAGBA","t":"1"}]},
  {n:"Mecs Blossom Ent",a:[{"l":"Igbogbo Bayeku","w":"SLOT B,WARD C2 IGBOGBO","t":"2"}]},
  {n:"Metropolitan",a:[{"l":"Agbado Oke-Odo","w":"AGBELEKALE II","t":"2"}]},
  {n:"Micbee Global",a:[{"l":"Apapa","w":"IJORA OLOYE","t":"1"}]},
  {n:"Microwaste Nigeria Limited",a:[{"l":"Iru/ Victoria Island","w":"FROM PART OF OZUMBA MBADIWE TO SAMUEL MANUWA, BALARABE MUSA, BABTUNDE JOSE, BISHOP ABOYADE COLE, BENDEL CLOSE, ITIRIN COURT, MURI OKUNOLA, ETIM IYANG CRESCENT","t":"2"}]},
  {n:"Mid Royal Global Services",a:[{"l":"Ifako Ijaiye","w":"IFAKO COKER","t":"2"}]},
  {n:"Miladex Nig Ltd",a:[{"l":"Olorunda","w":"ARADAGUN -BADAGRY (L )","t":"2"}]},
  {n:"Mobalko Ventures",a:[{"l":"Ibeju Lekki","w":"BOJIGE - ALAHUN (BOTH SIDES)","t":"2"}]},
  {n:"Modesire",a:[{"l":"Eti-Osa East","w":"ADDO R/ABOUT TO LOTHAM NUR & PRY SCHOOL","t":"2"}]},
  {n:"Mubirabshol Ltd",a:[{"l":"Ifako Ijaiye","w":"IJU ISHAGA II","t":"2"}]},
  {n:"Muiz & Karis",a:[{"l":"Egbe Idimu","w":"EGBE AGODO II","t":"2"}]},
  {n:"Muiz & Kariz",a:[{"l":"Orile Agege","w":"ISALE ODO","t":"1"}]},
  {n:"Murewa Integrated",a:[{"l":"Imota","w":"SLOT A IMOTA","t":"2"}]},
  {n:"Murphywins Limited",a:[{"l":"Ajeromi","w":"OLUWA II","t":"2"}]},
  {n:"Musimot Abike Davies",a:[{"l":"Coker Aguda","w":"SAVAGE","t":"1"}]},
  {n:"Mzo Resources",a:[{"l":"Iru/ Victoria Island","w":"1004 ESTATE","t":"2"}]},
  {n:"Nakod Ventures",a:[{"l":"Alimosho","w":"OGUNTADE/ BANMEKE","t":"0"}]},
  {n:"Nasbebag",a:[{"l":"Isolo","w":"ALAAGBEJI","t":"2"}]},
  {n:"New Dawn Cleaning Services",a:[{"l":"Ibeju Lekki","w":"AWOYAYA - ORIBANWA(LHS)","t":"2"}]},
  {n:"New Rossy Vent",a:[{"l":"Apapa Iganmu","w":"GASKIYA","t":"1"}]},
  {n:"Next To Godliness Ent",a:[{"l":"Amuwo Odofin","w":"ABULE ADO/TRADE FAIR","t":"3"},{"l":"Itire-Ikate","w":"SANUSI","t":"2"}]},
  {n:"Ngo Enterprises",a:[{"l":"Ori-Ade","w":"AGBOJU","t":"2"}]},
  {n:"Nigerian Cleaning Services",a:[{"l":"Lagos Mainland","w":"ALABA / DESALU","t":"1"}]},
  {n:"Nikeron Ltd",a:[{"l":"Somolu","w":"IJEBUTEDO","t":"2"}]},
  {n:"Nimat Multilinks",a:[{"l":"Badagry Central","w":"TOPO-IDALE","t":"1"}]},
  {n:"Nobal Ventures",a:[{"l":"Ayobo Ipaja","w":"ISHEFUN","t":"2"}]},
  {n:"Notob Nig Ent",a:[{"l":"Ijede","w":"WARD B","t":"1"}]},
  {n:"Novateur Logistics",a:[{"l":"Ibeju Lekki","w":"AKODO - IDASHO","t":"1"}]},
  {n:"Nureni Saka Enterprises",a:[{"l":"Isolo","w":"ILASAMAJA","t":"4"},{"l":"Itire-Ikate","w":"ODO OLOWU","t":"2"}]},
  {n:"O & O Ventures",a:[{"l":"Ojokoro","w":"JANKARA","t":"3"}]},
  {n:"Ola Trans Athlantic",a:[{"l":"Agbado Oke-Odo","w":"AGBELEKALE III","t":"1"}]},
  {n:"Olajendor International",a:[{"l":"Ikorodu North","w":"AGBALA","t":"3"}]},
  {n:"Olamper",a:[{"l":"Eti Osa West","w":"OKUN AJAH C","t":"2"}]},
  {n:"Olamper Environmental",a:[{"l":"Igbogbo Bayeku","w":"SLOT B EWU ELEPE (GINTI-OLOJA , RIGHT)","t":"1"}]},
  {n:"Olamper Envronmental",a:[{"l":"Ikorodu North","w":"ITAMAGA","t":"2"}]},
  {n:"Olaolu Gracex",a:[{"l":"Alimosho","w":"EGBEDA","t":"3"}]},
  {n:"Olaoluwakitan Ventures",a:[{"l":"Ikorodu West","w":"OKE OKO","t":"1"}]},
  {n:"Olasham Waste",a:[{"l":"Kosofe","w":"MENDE, MARYLAND","t":"3"}]},
  {n:"Olashams Waste Company",a:[{"l":"Ikeja","w":"ONILEKERE","t":"3"}]},
  {n:"Olasup Ventures",a:[{"l":"Ikorodu West","w":"MAJIDUN/OGOLONTO","t":"1"}]},
  {n:"Oluadetayo Nig. Ent.",a:[{"l":"Ikorodu West","w":"ISAWO","t":"2"}]},
  {n:"Olutoye Glorious",a:[{"l":"Egbe Idimu","w":"ISHERI OLOFIN II","t":"2"}]},
  {n:"Oluwabunmi Toyin Ent",a:[{"l":"Lagos Mainland","w":"IPONRI/OLALEYE","t":"1"}]},
  {n:"Oluwaseun Investment Companyy Ltd",a:[{"l":"Amuwo Odofin","w":"EKO AKETE","t":"6"}]},
  {n:"Oluwatosin Ventures",a:[{"l":"Onigbongbo","w":"ONIGBONGBO I","t":"1"}]},
  {n:"Omeja Golden",a:[{"l":"Iba","w":"KEMBERI WARD","t":"1"}]},
  {n:"Omojak Gold Enterprises",a:[{"l":"Agege","w":"ISALE OJA","t":"2"}]},
  {n:"Onirakunmi Ent",a:[{"l":"Ifako Ijaiye","w":"IFAKO OKE IRA","t":"2"}]},
  {n:"Open Door Systems",a:[{"l":"Ojodu","w":"OMOLE PHASE I","t":"3"}]},
  {n:"Owoigbe Kirun",a:[{"l":"Mosan Okunola","w":"MOSAN/ AKINOGUN II","t":"2"}]},
  {n:"Oye Balogun & Sons",a:[{"l":"Ojokoro","w":"ABULE EGBA","t":"3"}]},
  {n:"Oyindamola",a:[{"l":"Eti Osa West","w":"ILASAN COMMUNITY(AARE BASHIR FAKOREDE ROAD)","t":"1"}]},
  {n:"Oyinlar Intl Ltd",a:[{"l":"Oto Awori","w":"WARD A II","t":"1"}]},
  {n:"Padaao Ent",a:[{"l":"Agege","w":"PAPA UKU","t":"1"}]},
  {n:"Panacea Introserve Concepts",a:[{"l":"Mushin Ajina","w":"MOSHALASHI AGORO","t":"2"}]},
  {n:"Pe Alafia",a:[{"l":"Igando Ikotun","w":"EGAN I","t":"2"}]},
  {n:"Peidmount",a:[{"l":"Ikeja","w":"LSDPC SHOPRITE ALAUSA","t":"0"}]},
  {n:"Pepat Technical",a:[{"l":"Oshodi","w":"EWU TUNTUN","t":"2"}]},
  {n:"Pesjoy Ventures",a:[{"l":"Ejigbo","w":"BUCKNOR II","t":"1"}]},
  {n:"Peter & Precious Ent.",a:[{"l":"Ikorodu Central","w":"ITA ELEWA","t":"2"}]},
  {n:"Peter Bradford & Associates",a:[{"l":"Onigbongbo","w":"OREGUN","t":"4"}]},
  {n:"Precious Addy",a:[{"l":"Ori-Ade","w":"IJEGUN EGBA","t":"3"}]},
  {n:"Prochford Ventures Limited",a:[{"l":"Ikeja","w":"ALAUSA","t":"2"}]},
  {n:"Proficient Logistics Services",a:[{"l":"Somolu","w":"OKESUNA/ALASE (WARD E)","t":"1"},{"l":"Somolu","w":"ORILE SHOMOLU ALADE(WARD D)","t":"2"}]},
  {n:"Provident Global Solution",a:[{"l":"Ejigbo","w":"IFOSHI","t":"3"}]},
  {n:"Pytermag",a:[{"l":"Lagos Mainland","w":"BOTANICAL GARDEN","t":"1"}]},
  {n:"Rashmeed Ventures",a:[{"l":"Igando Ikotun","w":"AKESAN II","t":"2"}]},
  {n:"Raylaw Global Services",a:[{"l":"Eti Osa West","w":"ALPHA CIRCLE EVENT CENTRE(ALTERNATIVE ROUTE) TO NORTHWEST FILLING STATION","t":"2"}]},
  {n:"Remo 2020 Solutions",a:[{"l":"Mosan Okunola","w":"OKUNOLA I","t":"2"}]},
  {n:"Richbol  Environmental Services Ltd",a:[{"l":"Somolu","w":"BASHUA EAST/WEST","t":"1"},{"l":"Somolu","w":"IGBOBI/FADEYI","t":"1"}]},
  {n:"Richknot Ventures",a:[{"l":"Ikorodu North","w":"SLOT B AGBEDE","t":"1"}]},
  {n:"Rico Clean",a:[{"l":"Eti Osa West","w":"OKUN AJAH/ MAPO D","t":"2"}]},
  {n:"Ricommy Ent",a:[{"l":"Oto Awori","w":"ILOGBO","t":"1"}]},
  {n:"Rising Star Technical Limited",a:[{"l":"Odi-Olowo Ojuwoye","w":"KAYODE/FADEYI","t":"2"}]},
  {n:"Robobond",a:[{"l":"Ori-Ade","w":"SATELLITE SLOT A","t":"1"}]},
  {n:"Romila Investment Ltd",a:[{"l":"Ikeja","w":"ALAUSA/ OREGUN","t":"1"}]},
  {n:"Rotkas Nig Ltd",a:[{"l":"Coker Aguda","w":"NURU ONIWO","t":"2"}]},
  {n:"Royal Integrated",a:[{"l":"Egbe Idimu","w":"EGBE LIASU","t":"2"}]},
  {n:"Ryan Agro Retail Services",a:[{"l":"Isolo","w":"AGO PALACE WAY MEDIAN (FROM NEW JERUSALEM (AFETR BRIDGE) TO OKOTA ROAD(OPPOSITE CHICKEN REPUBLIC)","t":"2"}]},
  {n:"Saab Global",a:[{"l":"Eti Osa West","w":"SAFE COURT, THE ATLANTIS, SPRINGVILLE, MEGAMOUND, VINTAGE PARK ESTATES ALONG OJULARI ROAD ABD CRESCENT OFF PALM SPRING ROAD, IKATE","t":"1"}]},
  {n:"Saab Global Ltd",a:[{"l":"Iru/ Victoria Island","w":"DIDEOLU ESTATE","t":"2"}]},
  {n:"Samelu Nig. Ent.",a:[{"l":"Ikorodu North","w":"ERIKORODO/ERUNWEN","t":"2"}]},
  {n:"Sampaslog Limited",a:[{"l":"Isolo","w":"STARTIMES ESTATE","t":"1"}]},
  {n:"Samspalog",a:[{"l":"Ajeromi","w":"IBAFON","t":"2"}]},
  {n:"Sanitation Solution",a:[{"l":"Bariga","w":"GBAGADA/OBANIKORO","t":"2"}]},
  {n:"Sanitizers Vventures",a:[{"l":"Ojokoro","w":"AGBADO KOLLINGTON","t":"2"},{"l":"Ojokoro","w":"IJAIYE/OJOKORO","t":"3"}]},
  {n:"Sarobol Nig.Ltd",a:[{"l":"Kosofe","w":"ANTHONY","t":"4"}]},
  {n:"Sarobol Nigeria Limited",a:[{"l":"Isolo","w":"OKOTA","t":"2"}]},
  {n:"Say Super Global Services",a:[{"l":"Ojodu","w":"OJODU","t":"3"}]},
  {n:"Selmic Global Resources",a:[{"l":"Ajeromi","w":"IBAFON II (CSR)","t":"1"}]},
  {n:"Semase And Sons",a:[{"l":"Kosofe","w":"OJOTA","t":"4"}]},
  {n:"Semolink Vventures",a:[{"l":"Ojokoro","w":"OKO OBA I","t":"2"}]},
  {n:"Shafat Global Vent",a:[{"l":"Itire-Ikate","w":"AGUNBIADE","t":"1"}]},
  {n:"Shekayate Global",a:[{"l":"Ikorodu Central","w":"SLOT B AGA OJOMU","t":"2"}]},
  {n:"Shekaz Global Limited",a:[{"l":"Isolo","w":"ISHAGA/IRE AKARI","t":"2"}]},
  {n:"Shinaola Ventures",a:[{"l":"Egbe Idimu","w":"ISHERI OLOFIN III","t":"2"},{"l":"Iba","w":"IBA I","t":"3"},{"l":"Iba","w":"IGBO ELERIN","t":"3"}]},
  {n:"Shukurah Enterprises",a:[{"l":"Ayobo Ipaja","w":"SLOT A AYOBO","t":"2"}]},
  {n:"Sleyfo Nigeria Limited",a:[{"l":"Lagos Mainland","w":"OKO BABA","t":"1"}]},
  {n:"Smooth Vision",a:[{"l":"Eti-Osa East","w":"FROM OKE IRA BRIDGE TO ADO ROUND ABOUT/PART OF LANGBASA","t":"1"}]},
  {n:"Solab Nig Ltd",a:[{"l":"Surulere","w":"BABATUNDE/AYILARA","t":"2"}]},
  {n:"Soladex Ventures",a:[{"l":"Epe","w":"EPE A1 - A6","t":"3"}]},
  {n:"Spallete",a:[{"l":"Agbado Oke-Odo","w":"COMMAND I","t":"2"}]},
  {n:"Spc Pattern",a:[{"l":"Igando Ikotun","w":"IJEGUN II","t":"2"}]},
  {n:"St Mathew Daniel Consulting",a:[{"l":"Bariga","w":"APELEHIN","t":"2"}]},
  {n:"Stable Cleaning Services",a:[{"l":"Lagos Island East","w":"ARAROMI ODO","t":"4"}]},
  {n:"Standard Purity Vent",a:[{"l":"Orile Agege","w":"OYEWOLE ALAAGBA","t":"3"},{"l":"Orile Agege","w":"PAPA ASHAFA I","t":"2"}]},
  {n:"Strathmore",a:[{"l":"Ifako Ijaiye","w":"IFAKO PELE","t":"2"}]},
  {n:"Superior Waste Solution",a:[{"l":"Ojodu","w":"AKIODE II","t":"2"}]},
  {n:"Svv International",a:[{"l":"Iru/ Victoria Island","w":"EKO ATLANTIC","t":"2"}]},
  {n:"TK & P Associates",a:[{"l":"Agege","w":"KEKE I","t":"2"}]},
  {n:"Taborah Ventures Ltd",a:[{"l":"Onigbongbo","w":"WASIMI","t":"2"}]},
  {n:"Tajudeen Babatunde Taoreed And Sons",a:[{"l":"Eti Osa West","w":"ALPHA BEACH ROAD-IGBO EFON (LEFT)","t":"2"}]},
  {n:"Takar Nig Company",a:[{"l":"Ayobo Ipaja","w":"IPAJA","t":"2"}]},
  {n:"Taser Int'L",a:[{"l":"Kosofe","w":"MEDINA ESTATE","t":"1"}]},
  {n:"Tee Black Vent",a:[{"l":"Itire-Ikate","w":"BARUWA","t":"2"}]},
  {n:"Temi Adams & Associates",a:[{"l":"Orile Agege","w":"AYIGE","t":"2"}]},
  {n:"Temi Environmental",a:[{"l":"Onigbongbo","w":"OPEBI","t":"7"}]},
  {n:"Temmy Ventures",a:[{"l":"Yaba","w":"ONIKE OYADIRAN","t":"2"}]},
  {n:"Tfanklyn",a:[{"l":"Ajeromi","w":"AWODIORA I","t":"2"}]},
  {n:"Tfob Global Inv. Ltd",a:[{"l":"Surulere","w":"MOSAFEJO/OJUELEGBA","t":"1"}]},
  {n:"The Next Iinfrastrure",a:[{"l":"Iru/ Victoria Island","w":"KOFO ABAYOMI STREET (BOTH SIDES)","t":"1"}]},
  {n:"Theesoons Investments",a:[{"l":"Somolu","w":"ONIPANU","t":"2"}]},
  {n:"Tidy Tilden Nigeria Limited",a:[{"l":"Eti-Osa East","w":"BANANA ISLAND (Commenced work effective 15th of March , 2026)","t":"2"}]},
  {n:"Timitofu Nigeria Limited",a:[{"l":"Igbogbo Bayeku","w":"IGBE LAARA","t":"1"}]},
  {n:"Titabif Nigeria Limited",a:[{"l":"Eti Osa West","w":"ILASAN ORILE E","t":"4"}]},
  {n:"Toch And Clean",a:[{"l":"Ikoyi/ Obalende","w":"OSBORNE FORESHORE PHASE I & II","t":"2"}]},
  {n:"Tollydave Ventures",a:[{"l":"Lagos Mainland","w":"RAILWAY COMPOUND","t":"1"},{"l":"Yaba","w":"ABULE-IJESHA COMMUNITY","t":"1"}]},
  {n:"Tom Brown Ventures",a:[{"l":"Mushin Ajina","w":"ODO ERAN/OGUNLANA","t":"3"}]},
  {n:"Topdel",a:[{"l":"Agbado Oke-Odo","w":"COMMAND II","t":"2"}]},
  {n:"Toskad Enterprises",a:[{"l":"Odi-Olowo Ojuwoye","w":"ILUPEJU","t":"3"}]},
  {n:"Tram Waste",a:[{"l":"Agbado Oke-Odo","w":"AMIKANLE I","t":"2"}]},
  {n:"Tripple Hay Company",a:[{"l":"Somolu","w":"BAJULAIYE","t":"2"}]},
  {n:"Tunap Waste Company",a:[{"l":"Oshodi","w":"IGBEHIN ADUN","t":"3"},{"l":"Oshodi","w":"SHOGUNLE","t":"3"}]},
  {n:"Twincrown",a:[{"l":"Onigbongbo","w":"ONIGBONGBO II","t":"2"}]},
  {n:"Uba Remegius Ekene",a:[{"l":"Ifelodun","w":"APASA","t":"0"}]},
  {n:"Ultimate Steve",a:[{"l":"Agbado Oke-Odo","w":"AGBELEKALE I","t":"2"}]},
  {n:"Unidelsa Nigeria Limited",a:[{"l":"Eti Osa West","w":"ADMIRALTY WAY FROM ROAD 14 ALL LEFT TO FREEDOM WAY AND FOLA OSIBO ALL LEFT TO FREEDOM WAY","t":"2"}]},
  {n:"Union Waste Ventures",a:[{"l":"Yaba","w":"ABULE OJA/IJESHA","t":"1"}]},
  {n:"Unique Libra",a:[{"l":"Eti Osa West","w":"OKUN AJAH B","t":"3"}]},
  {n:"United Mapp",a:[{"l":"Egbe Idimu","w":"UNITY ESTATE I","t":"2"}]},
  {n:"Universal Care Limited",a:[{"l":"Isolo","w":"APENA","t":"4"}]},
  {n:"Urban Spirit Ventures",a:[{"l":"Onigbongbo","w":"GRA","t":"15"}]},
  {n:"Veedic Nigeria Limited",a:[{"l":"Ejigbo","w":"OKE AFA","t":"3"}]},
  {n:"Veraklean Services",a:[{"l":"Ajeromi","w":"TOLU","t":"2"}]},
  {n:"Verifocal Limited",a:[{"l":"Agboyi Ketu","w":"OWODE ONIRIN, OTERUBI OGIDAN, SUMOLA BAKO","t":"1"},{"l":"Ikosi Isheri","w":"GOD FIRST CDA/OWODE ELEDE AND ENVIRONS","t":"1"}]},
  {n:"Vestige",a:[{"l":"Ifako Ijaiye","w":"IFAKO/OYEMEKUN","t":"2"}]},
  {n:"Vuitton",a:[{"l":"Ibeju Lekki","w":"SANGOTEDO - ABIJO (LEFT SIDE)","t":"5"}]},
  {n:"Walirabsot Ltd",a:[{"l":"Bariga","w":"OWODE ORILE","t":"2"}]},
  {n:"Waste Infrastructure",a:[{"l":"Eti Osa West","w":"CHEVY VIEW ESTATE","t":"3"}]},
  {n:"Waste King",a:[{"l":"Ikosi Isheri","w":"IKOSI OKE","t":"2"}]},
  {n:"Wastepoint Limited",a:[{"l":"Iru/ Victoria Island","w":"WALTER CARINGTON, IDOWU MARTINS TO AHMADU BELLO WAY TO BISHOP OLUWOLE (EXCLUDING AKIN ADESOLA AND KOFO ABAYOMI)","t":"8"}]},
  {n:"Wawa International Vent Ltd",a:[{"l":"Surulere","w":"AKINHANMI","t":"1"}]},
  {n:"Wcb Ventures Ltd",a:[{"l":"Ifelodun","w":"ALABA","t":"1"}]},
  {n:"Wisegate Sleek",a:[{"l":"Ikoyi/ Obalende","w":"ALL BUILDING FROM ALEXANDER ROUNDABOUT JUNCTION(LEFT) TO LAWRENCE ROAD JUNCTION AND ALL INNER STREETS FROM LAWRENCE ROAD(RIGHT) TO BANKOLE CARDOZO STREET(RIGHT)","t":"2"}]},
  {n:"Wolag Global Nig. Ltd",a:[{"l":"Alimosho","w":"SHASHA","t":"2"}]},
  {n:"Worthline Limited",a:[{"l":"Iru/ Victoria Island","w":"ONIRU PRIVATE ESTATE","t":"3"}]},
  {n:"Xra Clean Services",a:[{"l":"Ikosi Isheri","w":"MAGODO/SHANGISHA","t":"5"}]},
  {n:"Xyz Nigeria Limited",a:[{"l":"Ibeju Lekki","w":"IBEJU LEKKI I -ABIJO TOWN (LEFT HAND SIDE) - AWOYAYA","t":"1"}]},
  {n:"Yard Systems",a:[{"l":"Eti Osa West","w":"FROM IKOYI BRIDGE ALL LEFT TO BABATUNDE ANJORIN AND ADMIRALTY ROAD TO FATAI IDOWU AROBIEKE","t":"2"}]},
  {n:"Yards System & Solution",a:[{"l":"Eti Osa West","w":"ORCHARD CLOSE, SCINTILLA ROAD, RO SUGARLAND RESTURANT & BAR ON CHEVRON ALTERNATIVE ROUTE","t":"2"}]},
  {n:"Yerima Cleaning & Maintanace",a:[{"l":"Ikosi Isheri","w":"ORILE KETU","t":"0"}]},
  {n:"Yet & Yem Enterprises",a:[{"l":"Ojokoro","w":"OKO OBA II","t":"3"},{"l":"Ojokoro","w":"PANADA","t":"3"}]},
  {n:"Yetlaw Environmental",a:[{"l":"Ojodu","w":"OGBA II /ADENIYI JONES","t":"3"}]},
  {n:"Yetlaw Environmental Services",a:[{"l":"Ikeja","w":"SERIKI ARO","t":"2"}]},
  {n:"Yinka Folson Nigeria Limited",a:[{"l":"Isolo","w":"ALAAGBEJI SLOT B","t":"2"}]},
  {n:"Zac-Olabeth",a:[{"l":"Eti Osa West","w":"JAKANDE FIRST GATE (LEFT)-IGBO EFON (RIGHT)","t":"1"}]},
  {n:"Zenith Waste",a:[{"l":"Igbogbo Bayeku","w":"OFIN/ORETA","t":"0"}]},
  {n:"Zone 7 Logistics Services",a:[{"l":"Ikosi Isheri","w":"ORILE IKOSI","t":"2"}]},
  {n:"Zonis Harriton",a:[{"l":"Oto Awori","w":"WARD A","t":"1"}]},
  {n:"Zulikha Bint Noah Investments Limited",a:[{"l":"Coker Aguda","w":"COKER","t":"2"}]},
];

var lagosLGAs = ["Agbado Oke-Odo", "Agboyi Ketu", "Agege", "Ajeromi", "Alimosho", "Amuwo Odofin", "Apapa", "Apapa Iganmu", "Ayobo Ipaja", "Badagry Central", "Badagry West", "Bariga", "Coker Aguda", "Egbe Idimu", "Ejigbo", "Epe", "Eredo", "Eti Osa West", "Eti-Osa East", "Iba", "Ibeju Lekki", "Ifako Ijaiye", "Ifelodun", "Igando Ikotun", "Igbogbo Bayeku", "Ijede", "Ikeja", "Ikorodu Central", "Ikorodu North", "Ikorodu West", "Ikosi Ejinrin", "Ikosi Isheri", "Ikoyi/ Obalende", "Imota", "Iru/ Victoria Island", "Isolo", "Itire-Ikate", "Kosofe", "Lagos Island East", "Lagos Island West", "Lagos Mainland", "Lekki Lcda", "Mosan Okunola", "Mushin Ajina", "Odi-Olowo Ojuwoye", "Ojo", "Ojodu", "Ojokoro", "Olorunda", "Onigbongbo", "Ori-Ade", "Orile Agege", "Oshodi", "Oto Awori", "Somolu", "Surulere", "Yaba"];